uploads = []
outputs = []

[[generated]]
id = "qJ27OR2xWpdrWRexylZdd"
uri = "file://artifacts/reforma-luxury/public/images/gallery-1.png"
type = "image"
title = "Luxury kitchen interior"

[[generated]]
id = "_ZP-VYZkrbEo-CDQHOjQ8"
uri = "file://artifacts/reforma-luxury/public/images/gallery-2.png"
type = "image"
title = "Luxury bathroom interior"

[[generated]]
id = "kvba060Rawv8qp5VicqQ8"
uri = "file://artifacts/reforma-luxury/public/images/gallery-3.png"
type = "image"
title = "Luxury living room"

[[generated]]
id = "Z5LFYk-DKi5pd-gLO2KNH"
uri = "file://artifacts/reforma-luxury/public/images/gallery-4.png"
type = "image"
title = "Luxury dining space"

[[generated]]
id = "42_6lPXT8ziPN0eRzVXwI"
uri = "file://artifacts/reforma-luxury/public/images/gallery-5.png"
type = "image"
title = "Luxury modern kitchen island"

[[generated]]
id = "wAdvJy4-bsi-P5b_fotOu"
uri = "file://artifacts/reforma-luxury/public/images/gallery-6.png"
type = "image"
title = "Luxury bedroom interior"

[[generated]]
id = "D4bz0zBtzorJJV-UZbv__"
uri = "file://artifacts/reforma-luxury/public/images/before.png"
type = "image"
title = "Rough room before renovation"

[[generated]]
id = "gNxSNz57DMmKMIVUNj6tB"
uri = "file://artifacts/reforma-luxury/public/images/after.png"
type = "image"
title = "Luxury room after renovation"
